meta_product_name: "Filao"
meta_title: "Filao - The perfect dashboard for freelancers"
meta_description: "Filao improves communication between freelancers and their clients."
meta_image: "facebook-card.jpg" # should exist in `app/assets/images/`
